version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mydemo-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: mydemo
      MYSQL_USER: mydemo
      MYSQL_PASSWORD: mydemo123
    command:
      - --slow_query_log=ON
      - --long_query_time=1
      - --log_output=FILE
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  my-demo:
    image: crpi-30y88bxc6uf0bne6.cn-guangzhou.personal.cr.aliyuncs.com/lin-demo/my-demo:latest
    container_name: my-demo
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydemo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: mydemo
      SPRING_DATASOURCE_PASSWORD: mydemo123
    volumes:
      - app-logs:/logs
    ports:
      - "8080:8080"
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: mydemo-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - my-demo
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: mydemo-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: mydemo-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: mydemo-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: always

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: mydemo-filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - app-logs:/var/log/myapp:ro
    depends_on:
      - elasticsearch
      - my-demo
    restart: always
  skywalking-oap:
    image: apache/skywalking-oap-server:9.6.0
    container_name: mydemo-skywalking-oap
    environment:
      - SW_STORAGE=h2
    ports:
      - "11800:11800"   # agent 上报 gRPC 端口
      - "12800:12800"   # UI / HTTP 查询端口
    restart: always

  skywalking-ui:
    image: apache/skywalking-ui:9.6.0
    container_name: mydemo-skywalking-ui
    environment:
      - SW_OAP_ADDRESS=http://skywalking-oap:12800
    ports:
      - "8088:8080"     # 浏览器访问 8088
    depends_on:
      - skywalking-oap
    restart: always

volumes:
  mysql-data:
  app-logs:
  es-data: