name: Java CI with Maven and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest   # 一定要是 ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run unit tests
        run: mvn -B clean test

      - name: Package without tests
        run: mvn -B -DskipTests package

      - name: List target directory
        run: ls -l target

      - name: Show Docker version
        run: docker version

      - name: Build Docker image
        run: |
          echo "Current dir: $(pwd)"
          ls
          docker build -t my-demo:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-demo
          docker tag my-demo:${{ github.sha }} $IMAGE_NAME:latest
          docker tag my-demo:${{ github.sha }} $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}